// Company facts are paraphrased from each linked first-party source, checked 2026-09-21.
// ALL membership, reviews, referrals and contributions are synthetic demo records.
export const categoryNames = [
  'Title Company',
  'Mortgage / Lender',
  'Home Inspector',
  'Home Warranty',
  'Plumber',
  'HVAC',
  'Electrician',
  'Roofing',
  'General Contractor',
  'Handyman',
  'Foundation',
  'Structural Engineer',
  'Pool / Spa',
  'Chimney / Fireplace',
  'Pest Control',
  'Termite',
  'Landscaping',
  'Lawn Care',
  'Tree Service',
  'Cleaning',
  'Carpet / Flooring',
  'Painting',
  'Windows / Glass',
  'Garage Door',
  'Locksmith',
  'Moving',
  'Storage',
  'Septic',
  'Sewer',
  'Drain',
  'Restoration / Water Damage',
  'Mold',
  'Environmental',
  'Surveyor',
  'Appraiser',
  'Insurance',
  'Photography / Media',
  'Other',
];
export const categoryId = (name: string) =>
  name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/-$/, '');
export const marketSeeds = [
  { id: 'tulsa', name: 'Tulsa Metro' },
  { id: 'okc', name: 'Oklahoma City Metro' },
  { id: 'wichita', name: 'Wichita Metro' },
  { id: 'other', name: 'Other' },
];
export const companySeeds = [
  {
    id: 'amc',
    name: 'AMC Mortgage',
    initials: 'AMC',
    tone: 'sage',
    categories: ['Mortgage / Lender'],
    markets: ['tulsa', 'okc'],
    other: '',
    website: 'https://amcmtg.com/',
    phone: '918-491-9900',
    email: '',
    contactName: '',
    description:
      'Mortgage services with Oklahoma locations in Tulsa and Oklahoma City. Connect with their team to discuss your home financing needs.',
    services: ['Home financing', 'Mortgage professionals', 'Loan calculators'],
    scores: [5, 5, 5, 5, 5, 5, 5, 5, 4, 5, 5, 5, 5, 5, 5, 5, 4, 5],
  },
  {
    id: 'executives',
    name: 'Executives Title',
    initials: 'ET',
    tone: 'sand',
    categories: ['Title Company'],
    markets: ['tulsa'],
    other: '',
    website: 'https://www.executivestitle.com/',
    phone: '918-745-9977',
    email: '',
    contactName: '',
    description:
      'Tulsa-area closing services for residential, commercial, and land transactions, with offices in Tulsa and Sapulpa.',
    services: [
      'Residential closings',
      'Commercial closings',
      'Land & ranch closings',
      '1031 exchange',
      'For sale by owner closings',
    ],
    scores: [5, 5, 5, 4, 5, 5, 5, 4, 5, 5, 5, 5],
  },
  {
    id: 'spartan',
    name: 'Spartan Home Inspection',
    initials: 'SH',
    tone: 'slate',
    categories: ['Home Inspector', 'Termite'],
    markets: ['tulsa'],
    other: '',
    website: 'https://www.spartaninspector.com/',
    phone: '918-888-6867',
    email: 'joseph@spartaninspector.com',
    contactName: '',
    description:
      'Residential home and termite inspections across Greater Tulsa, including Broken Arrow, Jenks, Bixby, Owasso, Sand Springs, Tahlequah, and Claremore.',
    services: ['Residential home inspections', 'Termite inspections', 'Inspection reports'],
    scores: [5, 5, 5, 5, 5, 5, 5, 5],
  },
  {
    id: 'achosa',
    name: 'Achosa Home Warranty',
    initials: 'AH',
    tone: 'clay',
    categories: ['Home Warranty'],
    markets: ['other'],
    other: 'Multi-market / National',
    website: 'https://www.achosahw.com/',
    phone: '888-509-2916',
    email: '',
    contactName: '',
    description:
      'Home protection service contracts for eligible major home systems and appliances. Homeowners can choose their own licensed contractors, subject to plan terms.',
    services: [
      'Home systems protection',
      'Appliance protection',
      'Homeowner-selected licensed contractors',
    ],
    scores: [5, 4, 5, 5, 4, 5, 5, 5, 4, 5],
  },
  {
    id: 'first-american',
    name: 'First American',
    initials: 'FA',
    tone: 'ocean',
    categories: ['Title Company', 'Home Warranty'],
    markets: ['other'],
    other: 'Multi-market / National',
    website: 'https://www.firstam.com/',
    phone: '',
    email: '',
    contactName: '',
    description:
      'Title insurance, settlement services, and other real-estate-related services. Its website also connects homeowners with First American home warranty services.',
    services: ['Title insurance', 'Settlement services', 'Real estate data', 'Home warranty'],
    scores: [],
  },
];
